			<ul id="navlist">
				<li class="<%if $current_action=="index"%>active<%/if%> nav1 "><a href="javascript:void(0);">基本信息</a></li>
				<li class="<%if $current_action=="environment"%>active<%/if%> nav2"><a href="javascript:void(0);">就餐环境</a></li>
				<li class="<%if $current_action=="category"%>active<%/if%> nav3"><a href="javascript:void(0);">菜单品类</a></li>
				<li class="<%if $current_action=="preferential"%>active<%/if%> nav4"><a href="javascript:void(0);">优惠设置</a></li>
				<li class="<%if $current_action=="takeaway"%>active<%/if%> nav5"><a href="javascript:void(0);">外送设置</a></li>
				<li class="<%if $current_action=="comments"%>active<%/if%> nav6"><a href="javascript:void(0);">用户评论</a></li>
			</ul>