
			<ul id="navlist">
				<li class="active nav1 "><a href="javascript:void(0);">基本信息</a></li>
				<li class="nav2"><a href="javascript:void(0);">就餐环境</a></li>
				<li class="nav3"><a href="javascript:void(0);">菜单品类</a></li>
				<li class="nav4"><a href="javascript:void(0);">优惠设置</a></li>
				<li class="nav5"><a href="javascript:void(0);">外送设置</a></li>
				<li class="nav6"><a href="javascript:void(0);">用户评论</a></li>
			</ul>